### ISSUE TITLE
Download Necessary NuGet Packages

### ISSUE THREAD

**Issue by khojianvar** [Biomed-uz/BioMed#25]

**Comment by Zikirillo2002** [comment]
Download the necessary NuGet Packages used in the BioMed.API project.

ACs :

1. Microsoft.EntityFrameworkCore   - v 8.00
2. Microsoft.EntityFrameworkCore.Tools   - v 8.00
3. Microsoft.EntityFrameworkCore.SqlServer   - v 8.00
4. Serilog - **latest version**
5. Serilog.AspNetCore   - v 8.00
6. Serilog.Sinks.Console - **latest version**
7. Serilog.Sinks.Debug - **latest version**
8. Serilog.Sinks.File - **latest version**
9. AutoMapper - **latest version**
10. AutoMapper.Extensions.Microsoft.DependencyInjection - **latest version**
11. Bogus - **latest version**
12. Newtonsoft.Json - **latest version**
13. Microsoft.AspNetCore.JsonPatch   - v 8.00
14. Microsoft.AspNetCore.Mvc.NewtonsoftJson   - v 8.00
15. Microsoft.AspNetCore.Authentication.JwtBearer   - v 8.00
16. Stripe.net - **latest version**
